Resources:
   myservice:
       Type: AWS::Serverless::Function
       Properties:
           CodeUri: ./build/run
           Handler: com.serverless.handler.Handler
           Runtime: java8
           MemorySize: 512
           Timeout: 300
           Environment:
               Variables:
                   AWS_REGION: sa-east-1
                   STAGE: local
                   DYNAMO_URL: http://localhost:37777
                   AWS_ACCESS_KEY_ID: local
                   AWS_SECRET_ACCESS_KEY: local